### ISSUE TITLE
analytic_tag_dimension error

### ISSUE THREAD

**Issue by ghost** [OCA/account-analytic#181]
When I try to save a Dimension this traceback appears:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo11e/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo11e/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo11e/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo11e/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo11e/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo11e/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo11e/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo11e/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo11e/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo11e/odoo/addons/web/controllers/main.py", line 931, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo11e/odoo/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo11e/odoo/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/odoo11e/odoo/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo11e/OCA/account-analytic/analytic_tag_dimension/models/analytic.py", line 37, in create
    'relation': 'account.analytic.tag',
  File "/opt/odoo11e/odoo/enterprise/web_studio/models/studio_mixin.py", line 27, in write
    res = super(StudioMixin, self).write(vals)
  File "/opt/odoo11e/odoo/addons/mail/models/ir_model.py", line 38, in write
    res = super(IrModel, self).write(vals)
  File "/opt/odoo11e/odoo/odoo/addons/base/ir/ir_model.py", line 208, in write
    return super(IrModel, self).write(vals)
  File "/opt/odoo11e/odoo/odoo/models.py", line 3090, in write
    self._write(old_vals)
  File "/opt/odoo11e/odoo/odoo/models.py", line 3228, in _write
    field.write(self.with_context(rel_context), vals[name])
  File "/opt/odoo11e/odoo/odoo/fields.py", line 2259, in write
    comodel.create(act[2])
  File "/opt/odoo11e/odoo/enterprise/web_studio/models/studio_mixin.py", line 18, in create
    res = super(StudioMixin, self).create(vals)
  File "/opt/odoo11e/odoo/odoo/addons/base/ir/ir_model.py", line 638, in create
    self.pool.init_models(self._cr, models, dict(self._context, update_custom_fields=True))
  File "/opt/odoo11e/odoo/odoo/modules/registry.py", line 311, in init_models
    func()
  File "/opt/odoo11e/odoo/odoo/fields.py", line 1956, in update_db_foreign_key
    new = process(model._cr, model._table, self.name, comodel._table, 'id', self.ondelete or 'set null')
  File "/opt/odoo11e/odoo/odoo/tools/sql.py", line 169, in fix_foreign_key
    cr.execute(query, (tablename1, columnname1))
  File "/opt/odoo11e/odoo/odoo/sql_db.py", line 154, in wrapper
    raise psycopg2.OperationalError(msg)
psycopg2.OperationalError: Unable to use a closed cursor.

**Comment by pedrobaeza** [comment]
Please provide full detailed steps to reproduce the problem on runbot (https://runbot.odoo-community.org)

**Comment by ghost** [comment]
![01](https://user-images.githubusercontent.com/25029267/42090220-e397024a-7ba0-11e8-88a1-64c370b9c142.png)
![01](https://user-images.githubusercontent.com/25029267/42090243-02cdc356-7ba1-11e8-83f0-9621f86bfd7c.png)
When I try to save it:
![01](https://user-images.githubusercontent.com/25029267/42090287-2d477b90-7ba1-11e8-8da8-ed985078c64c.png)
The traceback in this case is:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/OCB-11.0/addons/web/controllers/main.py", line 931, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/OCB-11.0/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/build/OCA/account-analytic/analytic_tag_dimension/models/analytic.py", line 37, in create
    'relation': 'account.analytic.tag',
  File "/home/odoo/OCB-11.0/addons/mail/models/ir_model.py", line 38, in write
    res = super(IrModel, self).write(vals)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_model.py", line 208, in write
    return super(IrModel, self).write(vals)
  File "/.repo_requirements/odoo/odoo/models.py", line 3090, in write
    self._write(old_vals)
  File "/.repo_requirements/odoo/odoo/models.py", line 3228, in _write
    field.write(self.with_context(rel_context), vals[name])
  File "/.repo_requirements/odoo/odoo/fields.py", line 2259, in write
    comodel.create(act[2])
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_model.py", line 638, in create
    self.pool.init_models(self._cr, models, dict(self._context, update_custom_fields=True))
  File "/.repo_requirements/odoo/odoo/modules/registry.py", line 311, in init_models
    func()
  File "/.repo_requirements/odoo/odoo/models.py", line 274, in _reflect
    self.env['ir.model']._reflect_model(self)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_model.py", line 247, in _reflect_model
    query_update(cr, self._table, params, ['model'])
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_model.py", line 54, in query_update
    cr.execute(query, values)
  File "/.repo_requirements/odoo/odoo/sql_db.py", line 154, in wrapper
    raise psycopg2.OperationalError(msg)
psycopg2.OperationalError: Unable to use a closed cursor.

**Comment by pedrobaeza** [comment]
@angelmoya you were the original author of this. Do you have any clue?

**Comment by angelmoya** [comment]
I had not seen this error before.

You can get it on runbot?

**Comment by ghost** [comment]
These screenshots are from runbot.
![01](https://user-images.githubusercontent.com/25029267/42090849-58663008-7ba3-11e8-9c0a-9b4f7e94f3a9.png)

**Comment by TheRealHatCoder** [comment]
Hi @angelmoya 

While trying to save the first time, you get below trace. 

```
Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 931, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo_addons/analytic_tag_dimension/models/analytic.py", line 37, in create
    'relation': 'account.analytic.tag',
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/ir_model.py", line 38, in write
    res = super(IrModel, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 208, in write
    return super(IrModel, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3090, in write
    self._write(old_vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3228, in _write
    field.write(self.with_context(rel_context), vals[name])
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2259, in write
    comodel.create(act[2])
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 638, in create
    self.pool.init_models(self._cr, models, dict(self._context, update_custom_fields=True))
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 307, in init_models
    model.init()
  File "/usr/lib/python3/dist-packages/odoo/addons/account/report/account_invoice_report.py", line 174, in init
    self._select(), self._sub_select(), self._from(), self._group_by()))
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column ail.x_dimension_soc does not exist
LINE 46:         , ail.x_dimension_SOC as x_dimension_SOC, ai.team_id...
                   ^
HINT:  Perhaps you meant to reference the column "ail.x_dimension_SOC".
```

Note that the "SOC" is the code I associated.
![image](https://user-images.githubusercontent.com/30595027/42772610-3edb93cc-892b-11e8-9599-7c8d90ac7a53.png)


@gelo-landoo's trace only appears if you do the same, without restarting Odoo instance.

Hope this helps.

**Comment by ghost** [comment]
Hello @BIZ4Africa ,
Sorry for my late response. When do you have to restart the Odoo instance?Each time a dimension is created?
Thanks,

**Comment by erictang0825** [comment]
This issue is fixed?
i get the same error today!

**Comment by ghost** [comment]
I think it's not

**Comment by jaumeplanas** [comment]
I'm experiencing the same error `psycopg2.ProgrammingError: column ail.x_dimension_soc`.

After debugging a while, in `account.analytic.dimension.create` function, `model_names` contains a **set** of model names. Then, when executing `search` function, another unordered set is returned. In this recordset, *account.invoice.report* should be called **after** *account.invoice.line*, because the former is expecting fields defined in the latter. Since **set**  and the recordset aren't ordered sequences, this dependency is not garanteed.

I think `def create(self)` function should be rewritten in order to garantee this order of models/fields creation.

**Comment by robinhli** [comment]
I have both issue described above.
    raise psycopg2.OperationalError(msg)
psycopg2.OperationalError: Unable to use a closed cursor.

psycopg2.ProgrammingError: 错误:  字段 ail.x_dimension_product 不存在
LINE 46:         , ail.x_dimension_Product as x_dimension_Product, ai...

**Comment by jalzaga** [comment]
The error is still not fixed. I tried on runbot today and I obtained the following error
`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 747, in call_kw
    return _call_kw_model_create(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 727, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-253>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 430, in _model_create_single
    return create(self, arg)
  File "/home/odoo/build/OCA/account-analytic/analytic_tag_dimension/models/analytic.py", line 38, in create
    'relation': 'account.analytic.tag',
  File "/home/odoo/OCB-12.0/addons/mail/models/ir_model.py", line 63, in write
    res = super(IrModel, self).write(vals)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_model.py", line 235, in write
    return super(IrModel, self).write(vals)
  File "/.repo_requirements/odoo/odoo/models.py", line 3321, in write
    self._write(store_vals)
  File "/.repo_requirements/odoo/odoo/models.py", line 3451, in _write
    field.write(other, vals[field.name])
  File "/.repo_requirements/odoo/odoo/fields.py", line 2529, in write
    flush()
  File "/.repo_requirements/odoo/odoo/fields.py", line 2490, in flush
    comodel.create(vals_list)
  File "<decorator-gen-20>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 433, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/.repo_requirements/odoo/odoo/api.py", line 433, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_model.py", line 712, in create
    self.pool.init_models(self._cr, models, dict(self._context, update_custom_fields=True))
  File "/.repo_requirements/odoo/odoo/modules/registry.py", line 301, in init_models
    func()
  File "/.repo_requirements/odoo/odoo/fields.py", line 2118, in update_db_foreign_key
    new = process(model._cr, model._table, self.name, comodel._table, 'id', self.ondelete or 'set null')
  File "/.repo_requirements/odoo/odoo/tools/sql.py", line 177, in fix_foreign_key
    cr.execute(query, (tablename1, columnname1))
  File "/.repo_requirements/odoo/odoo/sql_db.py", line 147, in wrapper
    raise psycopg2.OperationalError(msg)
psycopg2.OperationalError: Unable to use a closed cursor.`
I followed the same steps: create a new analytic tag dimension. I atach a screenshot
![2019-07-15 12_18_31-analytic tag dimension](https://user-images.githubusercontent.com/7764079/61209762-e8d7c380-a6fa-11e9-9593-f148cba6e7cd.png)

**Comment by syci** [comment]
I get the same error in runbot 11.0 right now
http://3393941-11-0-8d27bf.runbot1.odoo-community.org/web?debug=1#id=2&view_type=form&model=account.analytic.dimension&menu_id=274&action=390

![account_dimmension_err](https://user-images.githubusercontent.com/7081394/68301436-df9ea800-0097-11ea-8cae-093349cebc59.gif)

> Traceback (most recent call last):
>   File "/.repo_requirements/odoo/odoo/http.py", line 653, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/.repo_requirements/odoo/odoo/http.py", line 312, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 87, in reraise
>     raise value
>   File "/.repo_requirements/odoo/odoo/http.py", line 695, in dispatch
>     result = self._call_function(**self.params)
>   File "/.repo_requirements/odoo/odoo/http.py", line 344, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/.repo_requirements/odoo/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/.repo_requirements/odoo/odoo/http.py", line 337, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/.repo_requirements/odoo/odoo/http.py", line 939, in __call__
>     return self.method(*args, **kw)
>   File "/.repo_requirements/odoo/odoo/http.py", line 517, in response_wrap
>     response = f(*args, **kw)
>   File "/home/odoo/OCB-11.0/addons/web/controllers/main.py", line 934, in call_kw
>     return self._call_kw(model, method, args, kwargs)
>   File "/home/odoo/OCB-11.0/addons/web/controllers/main.py", line 926, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/.repo_requirements/odoo/odoo/api.py", line 699, in call_kw
>     return call_kw_multi(method, model, args, kwargs)
>   File "/.repo_requirements/odoo/odoo/api.py", line 690, in call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "/.repo_requirements/odoo/odoo/models.py", line 3989, in copy
>     new = self.with_context(lang=None).create(vals)
>   File "/home/odoo/build/OCA/account-analytic/analytic_tag_dimension/models/analytic.py", line 37, in create
>     'relation': 'account.analytic.tag',
>   File "/home/odoo/OCB-11.0/addons/mail/models/ir_model.py", line 38, in write
>     res = super(IrModel, self).write(vals)
>   File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_model.py", line 211, in write
>     return super(IrModel, self).write(vals)
>   File "/.repo_requirements/odoo/odoo/models.py", line 3127, in write
>     self._write(old_vals)
>   File "/.repo_requirements/odoo/odoo/models.py", line 3270, in _write
>     field.write(self.with_context(rel_context), vals[name])
>   File "/.repo_requirements/odoo/odoo/fields.py", line 2290, in write
>     comodel.create(act[2])
>   File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_model.py", line 662, in create
>     self.pool.init_models(self._cr, models, dict(self._context, update_custom_fields=True))
>   File "/.repo_requirements/odoo/odoo/modules/registry.py", line 311, in init_models
>     func()
>   File "/.repo_requirements/odoo/odoo/fields.py", line 1970, in update_db_foreign_key
>     new = process(model._cr, model._table, self.name, comodel._table, 'id', self.ondelete or 'set null')
>   File "/.repo_requirements/odoo/odoo/tools/sql.py", line 169, in fix_foreign_key
>     cr.execute(query, (tablename1, columnname1))
>   File "/.repo_requirements/odoo/odoo/sql_db.py", line 154, in wrapper
>     raise psycopg2.OperationalError(msg)
> psycopg2.OperationalError: Unable to use a closed cursor.

**Comment by rjay1018** [comment]
Same error

![err](https://user-images.githubusercontent.com/5526244/68853540-2b46f680-0715-11ea-9f76-df83a4d91eb7.png)

**Comment by pedrobaeza** [comment]
This was fixed in 1178e14ba796c5d28f2605761b5f7119b02fd445. I'm closing now. Please check and if not, please reply.
